"""nova-hello-mw — A demo middleware that prints "Hello, World!" before every model call.

Auto-generated by nova-mw-builder-plugin.
"""

from __future__ import annotations

import logging
from collections.abc import Callable
from typing import Any

from langchain.agents.middleware.types import (
    AgentMiddleware,
    
)
from langchain.tools import tool

logger = logging.getLogger("nova.plugins.hello-mw")


# ── Middleware ─────────────────────────────────────────────────────────────────

class HelloMwMiddleware(AgentMiddleware):
    """A demo middleware that prints "Hello, World!" before every model call."""

def before_model(self, state, runtime) -> dict[str, Any] | None:
    """Runs before each model call."""
    # TODO: implement
    return None

async def abefore_model(self, state, runtime) -> dict[str, Any] | None:
    return self.before_model(state, runtime)


# ── Tool (optional) ───────────────────────────────────────────────────────────



# ── Command (optional) ────────────────────────────────────────────────────────



# ── Entry point ───────────────────────────────────────────────────────────────

def register() -> dict[str, Any]:
    """Return the plugin spec for nova_hello_mw."""
    return {
        "name": "nova_hello_mw",
        "version": "0.1.0",
        "description": "A demo middleware that prints "Hello, World!" before every model call.",
        "tools": [],
        "commands": [],
        "middleware": [
            {
                "instance": HelloMwMiddleware(),
                "slot": "before_shell",
            },
        ],
        "subagents": [],
    }
