"""Nova MW Builder Plugin — a subagent that builds middleware plugins.

This is a *meta-plugin*: it generates other plugins. The ``mw-builder``
subagent knows the full Middleware.md contract and can scaffold a complete,
installable Nova middleware plugin from a natural-language description.

Provides:
  • subagent → mw-builder (knows the middleware API, generates plugins)
  • tool    → scaffold_middleware_plugin (writes plugin files to disk)
  • command → /mw-build (quick dispatch to the builder)
"""

from __future__ import annotations

import logging
import os
import textwrap
from pathlib import Path
from typing import Any

from langchain.tools import tool

logger = logging.getLogger("nova.plugins.mw-builder")

# ── Templates ─────────────────────────────────────────────────────────────────

PYPROJECT_TOML_TEMPLATE = '''\
[project]
name = "{package_name}"
version = "0.1.0"
description = "{description}"
requires-python = ">=3.11"
dependencies = [
    "langchain-core>=1.0",
    "langchain>=1.0",
]

[project.entry-points."nova.plugins"]
{entry_point_name} = "{module_path}"

[build-system]
requires = ["setuptools>=77"]
build-backend = "setuptools.build_meta"
'''

INIT_PY_TEMPLATE = '''\
"""{module_docstring}

Auto-generated by nova-mw-builder-plugin.
"""

from __future__ import annotations

import logging
from collections.abc import Callable
from typing import Any

from langchain.agents.middleware.types import (
    AgentMiddleware,
    {imports}
)
from langchain.tools import tool

logger = logging.getLogger("nova.plugins.{log_name}")


# ── Middleware ─────────────────────────────────────────────────────────────────

class {middleware_class}(AgentMiddleware):
    """{middleware_docstring}"""

{hook_bodies}

# ── Tool (optional) ───────────────────────────────────────────────────────────

{tool_code}

# ── Command (optional) ────────────────────────────────────────────────────────

{command_code}

# ── Entry point ───────────────────────────────────────────────────────────────

def register() -> dict[str, Any]:
    """Return the plugin spec for {package_name}."""
    return {{
        "name": "{package_name}",
        "version": "0.1.0",
        "description": "{description}",
        "tools": [{tool_list}],
        "commands": [{command_list}],
        "middleware": [
            {{
                "instance": {middleware_class}(),
                "slot": "{slot}",
            }},
        ],
        "subagents": [],
    }}
'''

# ── Hook body templates ───────────────────────────────────────────────────────

HOOK_BODIES: dict[str, str] = {
    "before_agent": textwrap.dedent("""\
        def before_agent(self, state, runtime) -> dict[str, Any] | None:
            \"\"\"Runs once before the agent starts.\"\"\"
            # TODO: implement
            return None

        async def abefore_agent(self, state, runtime) -> dict[str, Any] | None:
            return self.before_agent(state, runtime)
    """),
    "before_model": textwrap.dedent("""\
        def before_model(self, state, runtime) -> dict[str, Any] | None:
            \"\"\"Runs before each model call.\"\"\"
            # TODO: implement
            return None

        async def abefore_model(self, state, runtime) -> dict[str, Any] | None:
            return self.before_model(state, runtime)
    """),
    "after_model": textwrap.dedent("""\
        def after_model(self, state, runtime) -> dict[str, Any] | None:
            \"\"\"Runs after each model response.\"\"\"
            # TODO: implement
            return None

        async def aafter_model(self, state, runtime) -> dict[str, Any] | None:
            return self.after_model(state, runtime)
    """),
    "after_agent": textwrap.dedent("""\
        def after_agent(self, state, runtime) -> dict[str, Any] | None:
            \"\"\"Runs once after the agent completes.\"\"\"
            # TODO: implement
            return None

        async def aafter_agent(self, state, runtime) -> dict[str, Any] | None:
            return self.after_agent(state, runtime)
    """),
    "wrap_model_call": textwrap.dedent("""\
        def wrap_model_call(
            self,
            request,
            handler: Callable,
        ):
            \"\"\"Wraps each model call. Use to inject context, retry, etc.\"\"\"
            # TODO: implement custom logic before/after handler(request)
            return handler(request)

        async def awrap_model_call(
            self,
            request,
            handler: Callable,
        ):
            return self.wrap_model_call(request, handler)
    """),
    "wrap_tool_call": textwrap.dedent("""\
        def wrap_tool_call(
            self,
            request,
            handler: Callable,
        ):
            \"\"\"Wraps each tool call. Use to monitor, compact, filter, etc.\"\"\"
            # TODO: implement custom logic before/after handler(request)
            return handler(request)

        async def awrap_tool_call(
            self,
            request,
            handler: Callable,
        ):
            return self.wrap_tool_call(request, handler)
    """),
}

# ── Slot mapping ──────────────────────────────────────────────────────────────

SLOT_MAP: dict[str, str] = {
    "before_agent": "before_agent",
    "before_model": "before_model",
    "after_model": "after_model",
    "after_agent": "after_agent",
    "wrap_model_call": "before_shell",
    "wrap_tool_call": "after_tools",
}

IMPORT_MAP: dict[str, str] = {
    "before_agent": "",
    "before_model": "",
    "after_model": "",
    "after_agent": "",
    "wrap_model_call": "ModelRequest, ModelResponse",
    "wrap_tool_call": "ToolCallRequest",
}


# ── Tool — scaffolds a middleware plugin ──────────────────────────────────────

@tool
def scaffold_middleware_plugin(
    plugin_name: str,
    description: str,
    hook_type: str = "wrap_model_call",
    slot: str = "",
    include_tool: bool = False,
    include_command: bool = False,
    output_dir: str = "",
) -> str:
    """Scaffold a complete Nova middleware plugin on disk.

    Creates a pip-installable Python package with pyproject.toml, package
    directory, and __init__.py containing the middleware class and register()
    entry point.

    Args:
        plugin_name: Short kebab-case name, e.g. "nova-my-mw".
        description: One-line description of what the middleware does.
        hook_type: Which middleware hook to implement. One of:
            "before_agent", "before_model", "after_model", "after_agent",
            "wrap_model_call", "wrap_tool_call".
        slot: Middleware slot in the stack. If empty, auto-chosen from hook_type.
        include_tool: If True, include a stub tool in the plugin.
        include_command: If True, include a stub /command in the plugin.
        output_dir: Directory to create the plugin in. Defaults to
            CWD/plugins/<plugin_name>.

    Returns:
        A summary of what was created.
    """
    # Validate hook_type
    if hook_type not in HOOK_BODIES:
        valid = ", ".join(HOOK_BODIES.keys())
        return (
            f"Invalid hook_type '{hook_type}'. Valid options: {valid}\n\n"
            "Tip: use 'wrap_model_call' to inject context into the system prompt,\n"
            "     'wrap_tool_call' to intercept tool results,\n"
            "     'before_model'/'after_model' for node-style hooks."
        )

    # Derive values
    package_name = plugin_name.replace("-", "_")
    entry_point_name = plugin_name
    module_path = f"{package_name}:register"
    module_docstring = f"{plugin_name} — {description}"
    log_name = package_name.replace("nova_", "").replace("_", "-")
    middleware_class = _to_pascal_case(plugin_name.replace("nova-", "")) + "Middleware"

    if not slot:
        slot = SLOT_MAP.get(hook_type, "before_shell")

    # Imports
    imports = IMPORT_MAP.get(hook_type, "")

    # Hook body
    hook_bodies = HOOK_BODIES[hook_type]

    # Tool stub
    tool_code = ""
    tool_list = ""
    if include_tool:
        tool_name = plugin_name.replace("-", "_") + "_action"
        tool_code = textwrap.dedent(f'''\
            @tool
            def {tool_name}(message: str = "") -> str:
                """Custom tool for {plugin_name}. Replace with real logic."""
                return f"{{message}} (from {plugin_name})"
        ''')
        tool_list = tool_name

    # Command stub
    command_code = ""
    command_list = ""
    if include_command:
        cmd_name = plugin_name.replace("nova-", "").replace("-", "_")
        command_code = textwrap.dedent(f'''\
            async def {cmd_name}_command(args: str) -> str:
                """/{cmd_name} [args] — custom command for {plugin_name}."""
                return f"{{args}} (from {plugin_name})"
        ''')
        command_list = (
            '{\n'
            f'                "name": "{cmd_name}",\n'
            f'                "description": "Custom command for {plugin_name}",\n'
            f'                "handler": {cmd_name}_command,\n'
            '            }'
        )

    # Determine output path
    if not output_dir:
        output_dir = str(Path.cwd() / "plugins" / plugin_name)
    plugin_root = Path(output_dir)
    src_dir = plugin_root / "src" / package_name

    # Create directories
    src_dir.mkdir(parents=True, exist_ok=True)

    # Write pyproject.toml
    pyproject_content = PYPROJECT_TOML_TEMPLATE.format(
        package_name=package_name,
        description=description,
        entry_point_name=entry_point_name,
        module_path=module_path,
    )
    (plugin_root / "pyproject.toml").write_text(pyproject_content, encoding="utf-8")

    # Write __init__.py
    init_content = INIT_PY_TEMPLATE.format(
        module_docstring=module_docstring,
        imports=imports,
        log_name=log_name,
        middleware_class=middleware_class,
        middleware_docstring=description,
        hook_bodies=hook_bodies,
        tool_code=tool_code,
        tool_list=tool_list,
        command_code=command_code,
        command_list=command_list,
        package_name=package_name,
        description=description,
        slot=slot,
    )
    (src_dir / "__init__.py").write_text(init_content, encoding="utf-8")

    # Write README.md
    readme = textwrap.dedent(f"""\
        # {plugin_name}

        {description}

        ## Install

        ```bash
        uv pip install -e plugins/{plugin_name}
        ```

        ## Enable

        In Nova: `/plugins` → select **{plugin_name}** → Enable → restart session.
    """)
    (plugin_root / "README.md").write_text(readme, encoding="utf-8")

    return (
        f"✅ Scaffolded middleware plugin at: {plugin_root}\n"
        f"\n"
        f"  Package name:  {package_name}\n"
        f"  Middleware:     {middleware_class} (hook: {hook_type}, slot: {slot})\n"
        f"  Tool:          {'yes' if include_tool else 'no'}\n"
        f"  Command:       {'yes' if include_command else 'no'}\n"
        f"\n"
        f"Install:\n"
        f"  uv pip install -e plugins/{plugin_name}\n"
        f"\n"
        f"Then enable in Nova via /plugins."
    )


# ── Command — /mw-build ───────────────────────────────────────────────────────

async def mw_build_command(args: str) -> str:
    """/mw-build <description of the middleware you want>

    Records the description and tells you how to invoke the mw-builder
    subagent (commands can't dispatch subagents — only the LLM can).
    """
    if not args.strip():
        return (
            "Usage: /mw-build <description>\n\n"
            "Describe the middleware you want, then ask the agent to use the "
            "mw-builder subagent, e.g.:\n"
            '  /mw-build a middleware that logs every tool call to a file\n'
            '  → then say: "use the mw-builder subagent to create that"\n\n'
            "Or skip the command entirely and just tell the agent directly:\n"
            '  "scaffold a middleware plugin called nova-tool-logger that '
            'logs every tool call, using wrap_tool_call"'
        )
    return (
        f"✅ Got it: {args}\n\n"
        f"Now tell the agent:\n"
        f'  "use the mw-builder subagent to create {args}"\n\n'
        f"The subagent will ask clarifying questions, then call "
        f"`scaffold_middleware_plugin` to write the files.\n\n"
        f"Or skip the subagent and ask the agent directly:\n"
        f'  "scaffold a middleware plugin that {args}"'
    )


# ── Subagent — mw-builder ─────────────────────────────────────────────────────

MW_BUILDER_PROMPT = """\
You are the **MW Builder** — a specialist that generates Nova middleware plugins.

## Your job

The user describes a middleware they want in natural language. You:

1. **Ask clarifying questions** if the description is ambiguous — e.g. which hook
   type, whether they want a tool or command alongside it, what slot to use.
2. **Call `scaffold_middleware_plugin`** with the right parameters to generate
   the plugin files on disk.
3. **Summarise** what was created and how to install/enable it.

## Middleware API reference

### Available hooks

| Hook | Type | When it runs |
|------|------|-------------|
| `before_agent` | node-style | Once before the agent starts |
| `before_model` | node-style | Before each model call |
| `after_model` | node-style | After each model response |
| `after_agent` | node-style | Once after the agent completes |
| `wrap_model_call` | wrap-style | Around each model call — control execution |
| `wrap_tool_call` | wrap-style | Around each tool call — control execution |

### When to use each hook

- **`wrap_model_call`** — Inject dynamic context into the system prompt, retry
  on failure, switch models dynamically, filter/select tools. You get a
  `ModelRequest` with `.system_message`, `.messages`, `.model`, `.tools`, and
  `.state`. Return `handler(request.override(...))` to modify the call.

- **`wrap_tool_call`** — Monitor tool calls, compact long outputs, enforce
  permissions, add retry logic. You get a `ToolCallRequest` with `.tool_call`
  (dict with name/args/id) and `.state`. Return the result from `handler(request)`
  or a modified `ToolMessage`.

- **`before_model` / `after_model`** — Logging, validation, state tracking.
  Return a dict to update agent state. `before_model` can use `can_jump_to=["end"]`
  to short-circuit.

- **`before_agent` / `after_agent`** — Setup/teardown that runs once per
  invocation.

### Slots (where middleware sits in the stack)

| Slot | Position |
|------|----------|
| `before_shell` | Early — before ShellMiddleware (good for context injection) |
| `after_tools` | After tool execution (good for compacting results) |
| `before_tools` | Before tool execution (good for monitoring) |

Auto-selection if you don't specify:
- `wrap_model_call` → `before_shell`
- `wrap_tool_call` → `after_tools`
- `before_agent` / `before_model` → `before_shell`
- `after_model` / `after_agent` → `after_tools`

### Plugin structure

A generated plugin looks like:

```
plugins/<name>/
├── pyproject.toml          # Package metadata + nova.plugins entry point
├── README.md               # Install/enable instructions
└── src/<package_name>/
    └── __init__.py         # Middleware class + register() function
```

The `register()` function returns:
```python
{
    "name": "...",
    "version": "0.1.0",
    "description": "...",
    "tools": [...],          # optional
    "commands": [...],       # optional
    "middleware": [
        {"instance": MyMiddleware(), "slot": "before_shell"},
    ],
    "subagents": [],
}
```

## Guidelines

1. **Choose the right hook** based on what the user wants:
   - "inject context into the prompt" → `wrap_model_call`
   - "compact/truncate tool output" → `wrap_tool_call`
   - "log/model monitoring" → `after_model` or `wrap_model_call`
   - "rate limit / guard" → `before_model` with `can_jump_to=["end"]`
   - "setup before agent runs" → `before_agent`

2. **Use a descriptive plugin name** in kebab-case, prefixed with `nova-`.
   Examples: `nova-rate-limiter`, `nova-git-context`, `nova-output-filter`.

3. **Set `include_tool=True`** if the middleware needs a queryable companion
   tool (e.g. to inspect state). **Set `include_command=True`** if the user
   wants a `/command` to configure the middleware at runtime.

4. **Always call `scaffold_middleware_plugin`** to write the files — do not
   write them manually. The tool validates inputs and generates correct,
   installable output.

5. After scaffolding, tell the user:
   - The path to the generated plugin
   - The install command (`uv pip install -e plugins/<name>`)
   - That they need to enable it via `/plugins` and restart
"""


# ── Entry point ───────────────────────────────────────────────────────────────

def register() -> dict[str, Any]:
    """Return the plugin spec for nova-mw-builder-plugin."""
    return {
        "name": "nova-mw-builder-plugin",
        "version": "0.1.0",
        "description": (
            "A subagent that builds middleware plugins. Describe what you want "
            "in natural language and it scaffolds a complete, installable plugin."
        ),
        "tools": [scaffold_middleware_plugin],
        "commands": [
            {
                "name": "mw-build",
                "description": "Build a middleware plugin (/mw-build <description>)",
                "handler": mw_build_command,
            },
        ],
        "middleware": [],
        "subagents": [
            {
                "name": "mw-builder",
                "description": (
                    "Generates Nova middleware plugins from a natural-language "
                    "description. Knows all hook types, slots, and the plugin "
                    "contract. Scaffolds pyproject.toml, package, and register()."
                ),
                "system_prompt": MW_BUILDER_PROMPT,
                "tools": [scaffold_middleware_plugin],
            },
        ],
    }


# ── Helpers ───────────────────────────────────────────────────────────────────

def _to_pascal_case(name: str) -> str:
    """Convert kebab-case or snake_case to PascalCase."""
    return "".join(word.capitalize() for word in name.replace("-", "_").split("_"))
